packages:
  - "apps/*"
  - "lib-cli/*"
  - "lib-lint/*"
  - "lib-mcp/*"
  - "lib-nest/*"
  - "lib-react/*"
  - "lib-vue/*"
  - "libs/*"
  - "micro-frontend/*"
  - "micro-service/*"
  - "packages/*"
  - ".temp/*"
linkWorkspacePackages: true
# publish: registry
# strict: true
# hoistPattern: '@*'
# hoistDependents: true
# shamefullyHoist: true
# shamefullyFlatten: true
# packageManager: pnpm@7.22.0
# 一定要开启这个，不然无法自动安装workspace的依赖
# pnpm config set link-workspace-packages true

