# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdf_compress.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pdf_compress.proto\x12\x0cpdf_compress\"7\n\x0f\x43ompressRequest\x12\x13\n\x0bpdf_content\x18\x01 \x01(\x0c\x12\x0f\n\x07quality\x18\x02 \x01(\x05\"\x9b\x01\n\x10\x43ompressResponse\x12\x16\n\x0e\x63ompressed_pdf\x18\x01 \x01(\x0c\x12\x15\n\roriginal_size\x18\x02 \x01(\x03\x12\x17\n\x0f\x63ompressed_size\x18\x03 \x01(\x03\x12\x19\n\x11\x63ompression_ratio\x18\x04 \x01(\x02\x12\x13\n\x0bstatus_code\x18\x05 \x01(\x05\x12\x0f\n\x07message\x18\x06 \x01(\t\"D\n\x14\x42\x61tchCompressRequest\x12,\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1d.pdf_compress.CompressRequest\"\x8a\x01\n\x15\x42\x61tchCompressResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.pdf_compress.CompressResponse\x12\x13\n\x0btotal_files\x18\x02 \x01(\x05\x12\x15\n\rsuccess_count\x18\x03 \x01(\x05\x12\x14\n\x0c\x66\x61iled_count\x18\x04 \x01(\x05\x32\xc3\x01\n\x12PdfCompressService\x12N\n\x0b\x43ompressPdf\x12\x1d.pdf_compress.CompressRequest\x1a\x1e.pdf_compress.CompressResponse\"\x00\x12]\n\x10\x43ompressPdfBatch\x12\".pdf_compress.BatchCompressRequest\x1a#.pdf_compress.BatchCompressResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_compress_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPRESSREQUEST._serialized_start=36
  _COMPRESSREQUEST._serialized_end=91
  _COMPRESSRESPONSE._serialized_start=94
  _COMPRESSRESPONSE._serialized_end=249
  _BATCHCOMPRESSREQUEST._serialized_start=251
  _BATCHCOMPRESSREQUEST._serialized_end=319
  _BATCHCOMPRESSRESPONSE._serialized_start=322
  _BATCHCOMPRESSRESPONSE._serialized_end=460
  _PDFCOMPRESSSERVICE._serialized_start=463
  _PDFCOMPRESSSERVICE._serialized_end=658
# @@protoc_insertion_point(module_scope)
