# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pdf_compress_pb2 as pdf__compress__pb2


class PdfCompressServiceStub(object):
    """PDF压缩服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompressPdf = channel.unary_unary(
                '/pdf_compress.PdfCompressService/CompressPdf',
                request_serializer=pdf__compress__pb2.CompressRequest.SerializeToString,
                response_deserializer=pdf__compress__pb2.CompressResponse.FromString,
                )
        self.CompressPdfBatch = channel.unary_unary(
                '/pdf_compress.PdfCompressService/CompressPdfBatch',
                request_serializer=pdf__compress__pb2.BatchCompressRequest.SerializeToString,
                response_deserializer=pdf__compress__pb2.BatchCompressResponse.FromString,
                )


class PdfCompressServiceServicer(object):
    """PDF压缩服务定义
    """

    def CompressPdf(self, request, context):
        """压缩PDF文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompressPdfBatch(self, request, context):
        """批量压缩PDF文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PdfCompressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompressPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressPdf,
                    request_deserializer=pdf__compress__pb2.CompressRequest.FromString,
                    response_serializer=pdf__compress__pb2.CompressResponse.SerializeToString,
            ),
            'CompressPdfBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressPdfBatch,
                    request_deserializer=pdf__compress__pb2.BatchCompressRequest.FromString,
                    response_serializer=pdf__compress__pb2.BatchCompressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdf_compress.PdfCompressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PdfCompressService(object):
    """PDF压缩服务定义
    """

    @staticmethod
    def CompressPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pdf_compress.PdfCompressService/CompressPdf',
            pdf__compress__pb2.CompressRequest.SerializeToString,
            pdf__compress__pb2.CompressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompressPdfBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pdf_compress.PdfCompressService/CompressPdfBatch',
            pdf__compress__pb2.BatchCompressRequest.SerializeToString,
            pdf__compress__pb2.BatchCompressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
